export const URL = 'https://api.themoviedb.org/3/discover/movie?api_key=8d8e6405b1d127dcbe031bd2b3e85c3b&language=en-US&sort_by=popularity.desc&include_adult=false&include_video=false&page=1'
export const POSTER_PATH = 'http://image.tmdb.org/t/p/w500'
export const BACKDROP_PATH = 'http://image.tmdb.org/t/p/w1280'
export const FETCH_MOVIES = 'FETCH_MOVIES'
export const FETCH_MOVIEINFO = 'FETCH_MOVIEINFO'